---
- name: Declutter Windows
  import_playbook: declutter.yml

- name: Get the host ready for Gaming
  hosts: all

  tasks:
  - name: Ensure Opera is installed
    win_package:
      path: "https://net.geo.opera.com/opera/stable/windows"
      creates_path: "C:/Users/{{ username }}/AppData/Local/Programs/Opera/launcher.exe"
      arguments:
        - "/silent"

  - name: Ensure Visual Studio Code is installed
    win_package:
      path: "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user"
      creates_path: "C:/Users/Tim/AppData/Local/Programs/Microsoft VS Code/Code.exe"

  # Add automatically enabling Auto Sync in VSCode

  # From https://docs.ansible.com/ansible/2.9/modules/win_optional_feature_module.html#win-optional-feature-module 
  - name: Ensure Microsoft Subsystem for Linux is installed
  win_optional_feature:
    name: Microsoft-Windows-Subsystem-Linux
    state: present
  register: wsl_status

  - name: Reboot if installing Linux Subsytem as feature requires it
    win_reboot:
    when: wsl_status.reboot_required

  - name: Ensure Docker Desktop is installed
    win_package:
      path: "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe"
      arguments:
        - "install"
        - "--quiet"


